# Generated by Django 3.2.7 on 2021-11-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cheeseCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(
                    max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(
                    null=True, verbose_name='Описание')),
                ('price', models.DecimalField(
                    decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('width', models.CharField(max_length=255, verbose_name='Ширина')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='main_shop.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
